version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/work
    ports:
      - '3025:3025'
    container_name: graphql-app
    depends_on:
      - db
  db:
    image: postgres
    container_name: graphql-db
    volumes:
      - ./graph:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - '5432:5432'